Use define instead of static const int
Fixes MSVC Error C2057.

See https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2057