Fix void pointers arithmetic
Pointer arithmetic with void pointers works in GNU C by considering the size of the void as 1 hence it worked.

However the C standard doesn't allow pointer arithmetic with void pointers. Hence MSVC fails with Error C2036.