Raise C++ standard to C++20
Motivation:
In a few places, mostly code for the GPS filters, we use C++20 features already. Namely designated initializers aka. aggregate initialization (see https://en.cppreference.com/w/cpp/language/aggregate_initialization.html )

MSVC is very pick about this and hence fails with "error C7555: use of designated initializers requires at least "/std:c++20"."